spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_manager
    username: postgres
    password: "runi124t"

  liquibase:
    change-log: db/changelog/changelog.xml