spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: db/changelog/changelog.xml